#!/usr/bin/env python

#==============================================================================
# 3DEMscanner.py is part of 3DEMscanner suit software.
#
# 3DEMscanner is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# ParaScan is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Printrun. If not, see <http://www.gnu.org/licenses/>
#==============================================================================

""" Filename: EM3Dscanner.py

Authors: Radoslav Borisov
Contacts: radoslav (dot) borisov (at) gmail (dot) com

EM3Dscanner is a macro for ParaView for automation of measurement process of EM
waves with RepRap, Probe, PNA and ParaView
The scanner consists of:

    * Probe     - different probes are used for E and H vector of EM field
    * RepRap    - control the movement of the 'probe'
    * PNA       - measurements using Agilent N5230C Network Analyzer
    * ParaView  - data visualization software

Official web site: https://github.com/borisov-r/3DEMscanner/wiki

Basic functions that should be implemented:
    - create Wavelet() with arbitrary dimensions X, Y, Z
    - change PointData to CellData and work with CellData
    - save measured data to file
    - add / remove DataArray() to / from measured data

    scanner  main macro file, that controls the logic behind the measurements.

A simple example:
    # create Wavelet object
"""
import sys
sys.path.append('/home/radoslav/git/EM3Dscanner/src')
from paraview import vtk
from EM3Dnalib import NetworkAnalyzer
from EM3Dreprap import RepRap
from time import sleep


# both classes should stay in this file
class GetDimensionsList:
    """ This class is used to get the input for the measurement dimenssions
        and returns a list of the values for MyWavelet class.

        This is test class for now to so I can try
        GroupDatasets( Input=[ Measurement1, Measurement2 ] ) filter.
    """
    def __init__(self):
        # set dimensions manually
        # change dimensions of the cube (points to measure)
        #
        self.minusX = input("Enter value for -X: ")
        print(self.minusX)
        self.plusX = input("Enter value for X: ")
        print(self.plusX)
        #
        self.minusY = input("Enter value for -Y: ")
        print(self.minusY)
        self.plusY = input("Enter value for Y: ")
        print(self.plusY)
        #
        self.minusZ = input("Enter value for -Z: ")
        print(self.minusZ)
        self.plusZ = input("Enter value for Z: ")
        print(self.plusZ)

    def GetDimensions(self):
        """ return dimensions to be measured
        """
        return (self.minusX, self.plusX,
                self.minusY, self.plusY,
                self.minusZ, self.plusZ)


class MyWavelet:
    """ Initialize Wavelet() object with given dimensions
        and zeros as component values in the array.
        - Array name is set to 'Amplitude'
        - Rename Source to 'Measurement'
    """
    def __init__(self, dimensionsList):
        """ Initialize Wavelet() object with given dimensions.
            'dimensionsList' is a list generated by GetDimensionsList class
            GetDimensionsList.GetDimensions()
        """
        self.zero = 0                    # my zero in this class
        self.wave = Wavelet()
        #
        minusX = dimensionsList[0]
        plusX = dimensionsList[1]
        minusY = dimensionsList[2]
        plusY = dimensionsList[3]
        minusZ = dimensionsList[4]
        plusZ = dimensionsList[5]
        #
        self.wave.WholeExtent.SetData([minusX, plusX,
                                       minusY, plusY,
                                       minusZ, plusZ])
        # store dimensions in a tuple for later use
        self.dimensions = (minusX, plusX,
                           minusY, plusY,
                           minusZ, plusZ)
        #
        self.wave.Maximum = self.zero
        self.wave.XFreq = self.zero
        self.wave.YFreq = self.zero
        self.wave.ZFreq = self.zero
        self.wave.XMag = self.zero
        self.wave.YMag = self.zero
        self.wave.ZMag = self.zero
        self.wave.StandardDeviation = 0.5
        # this should stay like this StandardDeviation = 0.5 !
        # if StandardDeviation = 0 first element is NaN
        # and script is not working correctly

    def SetPointDataToCellData(self, waveletName):
        """ Make PointDataToCellData from generated Wavelet()
        Measurements are taken for CellData.
        Returns fetched data from the server.
        """
        # make PointData to CellData
        self.cellWave = PointDatatoCellData(self.wave)
        # fetch Data from the server
        self.fetchedCellWave = servermanager.Fetch(self.cellWave)
        self.fetchedCellWave.GetCellData().GetScalars().SetName(waveletName)
        RenameSource(waveletName)
        return self.fetchedCellWave

    def GetCellId(self, coordX, coordY, coordZ):
        """ Get CellID from coordinates in the volume.
        """
        # type(fetchCellWave) -> vtkImageData ->
        # -> fetcellCecellWave.ComputeCellId([9, 9, 9])
        id = self.fetchedCellWave.ComputeCellId([coordX, coordY, coordZ])
        return id

    def SetCellData(self, value, coordX, coordY, coordZ):
        """ Set CellData with 'value' to given cell, which is determined
            by its unique coordinates: coordX, coordY, coordZ
        """
        pointID = self.GetCellId(coordX, coordY, coordZ)
        setPoint = self.fetchedCellWave.GetCellData().GetScalars()
        setPoint.SetComponent(pointID, self.zero, float(value))
        self.cellWave.UpdatePipeline()

    def WriteToPVDFile(self, dataMode, name):
        """
        Write data to .pvd file.
        # The mode uses for writing the file's data i.e.
        # ascii = 0, binary = 1, appended binary = 2.
        example: WriteToPVDFile(0, 'test.pvd')
        """
        writer = servermanager.writers.XMLPVDWriter(FileName=name, DataMode=dataMode)
        writer.Input = GetActiveSource()
        writer.UpdatePipeline()
        return True

    def ShowAndRender(self):
        """ Calls Show() and Render() methods in ParaView
        """
        Show()
        Render()


dim = GetDimensionsList()
wave1 = MyWavelet(dim.GetDimensions())
wave1.SetPointDataToCellData("Amplitude")
wave2 = MyWavelet(dim.GetDimensions())
wave2.SetPointDataToCellData("Phase")
pna = NetworkAnalyzer("10.1.15.106", "5024")
reprap = RepRap()
reprap.connect("/dev/ttyACM0", 115200)
print "Wavelet dimensions: ", dim.GetDimensions()
reprap.setMeasureDimensions(dim.GetDimensions())
print "Number of points to measure: ", reprap.getNumberOfMeasurePoints()


if pna.connect() is True:
    pna.send("*IDN?")
    print pna.receive()
    #
    print("Current working folder: ")
    print pna.askPna("mmem:cdir?")
    #
    print("Load default displays and calibration.")
    pna.askPna("mmem:load 'calibrationRado.csa'")
    #
    print("Names and parameters of existing measurements for the specified channel:")
    print pna.askPna("calc:par:cat?")
    #
    # set data from pna to be ascii
    pna.askPna("format:data ascii")
    # set receive data to S11
    pna.askPna("calc:par:mnum 2")
    #
    print("Data format type: ")
    print pna.askPna("mmem:stor:trace:format:snp?")
    #
    print("Set format data to dB")
    pna.askPna("mmem:stor:trace:format:snp db")
    # receive data
    #print("Data received from PNA.")
    #data = pna.askPna("calc:data? fdata")
    #splitData = data.split(",")
    #print splitData
    # set first frequency point from pna to X-0, Y-0, Z-0
    #wave1.SetCellData(splitData[0], 0, 0, 0)
    #reprap.send_now("G1 X10")
    #wave2.SetCellData(splitData[0], 1, 0, 0)
    #reprap.send_now("G1 X10")
    # set second frequency point from pna to X-0, Y-0, Z-0
    #wave1.SetCellData(splitData[1], 9, 0, 0)
    #reprap.send_now("G1 X10")
    #wave2.SetCellData(splitData[1], 8, 0, 0)
    #reprap.send_now("G1 X10")
    reprap.moveOneCube(wave1, pna)


if pna.disconnect() is True:
    print("Disconnected from PNA.")
    reprap.disconnect()

# wave1.ShowAndRender()
# print wave1.dimensions
# wave1.WriteToPVDFile(0, "testPVD/myFirstPVD")
# data = GroupDatasets(Inputs=[Amplitude, Phase])
Show()
Render()
